In [ ]:
#Create NumPy Arrray

In [67]:
import numpy as np

In [68]:
a = np.array([1,2,3,4,5])
type(a)


numpy.ndarray

In [69]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [70]:
#sıfırdan array oluşturmak

In [71]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [73]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [74]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [75]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [76]:
np.random.normal(10,4,(3,4))

array([[ 7.03596833, 16.59641151,  3.22497581, 13.06206607],
       [ 9.06344879,  8.79840941,  5.86099375,  3.86743195],
       [ 8.80375843, 12.89519952,  5.63172588,  0.73877795]])

In [77]:
np.random.randint(0,10,(3,3))

array([[0, 1, 4],
       [7, 1, 4],
       [5, 8, 7]])

In [78]:
np.random.randint(10, size = 10)

array([0, 5, 2, 9, 8, 9, 5, 9, 5, 2])

In [79]:
# Numpy Array Features

In [80]:
a = np.random.randint(10, size = 10)

In [81]:
a.ndim

1

In [82]:
a.shape

(10,)

In [83]:
a.size

10

In [84]:
a.dtype

dtype('int64')

In [85]:
b = np.random.randint(10, size= (3,5))

In [86]:
b

array([[3, 3, 0, 8, 7],
       [8, 9, 5, 3, 4],
       [1, 9, 2, 6, 3]])

In [87]:
b.ndim

2

In [88]:
b.shape

(3, 5)

In [89]:
b.size

15

In [90]:
b.dtype

dtype('int64')

In [91]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
#Reshaping

In [94]:
a = np.arange(1,10)

In [95]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a.ndim

1

In [97]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [98]:
b = a.reshape((1,9))
b.ndim

2

In [99]:
#Concatenation

In [101]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [102]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [103]:
z = np.array([7,8,9])

In [104]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.concatenate([z,y,x])

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

In [109]:
a = np.array( [[1,2,3] , [4,5,6]])

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [112]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [113]:
#Splitting

In [114]:
x = np.array([1,2,3,99,99,3,2,1])

In [115]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [116]:
a,b,c = np.split(x,[3,5])

In [117]:
a

array([1, 2, 3])

In [118]:
b

array([99, 99])

In [119]:
c

array([3, 2, 1])

In [120]:
m = np.arange(16).reshape(4,4)

In [121]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [127]:
up_array,down_array = np.vsplit(m,[2])

In [129]:
up_array


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [130]:
down_array

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [131]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [132]:
left , right = np.hsplit(m,[2])

In [133]:
left


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [134]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
# Sorting Arrays

In [136]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [137]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [138]:
v

array([2, 1, 4, 3, 5])

In [140]:
v.sort()

In [141]:
v

array([1, 2, 3, 4, 5])

In [142]:
v

array([1, 2, 3, 4, 5])

In [143]:
# NUMPY IN İÇİNDE ÇAĞIRILIRSA YAPISINI BOZMAZ !!!!

In [144]:
m = np.random.normal(20,5,(3,3))

In [145]:
m

array([[21.49029486, 15.2717016 , 19.24956388],
       [22.61707743, 18.20584774, 28.02070277],
       [19.10972176, 14.60839165, 14.06944491]])

In [146]:
np.sort(m,axis=1)

array([[15.2717016 , 19.24956388, 21.49029486],
       [18.20584774, 22.61707743, 28.02070277],
       [14.06944491, 14.60839165, 19.10972176]])

In [147]:
np.sort(m,axis=0)

array([[19.10972176, 14.60839165, 14.06944491],
       [21.49029486, 15.2717016 , 19.24956388],
       [22.61707743, 18.20584774, 28.02070277]])

In [148]:
# Index materials

In [149]:
a = np.random.randint(10,size =(3,5))

In [150]:
a

array([[9, 1, 4, 3, 6],
       [6, 9, 4, 7, 5],
       [8, 3, 0, 8, 8]])

In [152]:
a[0,0]

np.int64(9)

In [153]:
a[1,1]

np.int64(9)

In [154]:
a[2,2]

np.int64(0)

In [155]:
a[0,0] = 100
a

array([[100,   1,   4,   3,   6],
       [  6,   9,   4,   7,   5],
       [  8,   3,   0,   8,   8]])

In [156]:
#Slicing

In [157]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [158]:
a[0:3]

array([20, 21, 22])

In [159]:
a[1::2]

array([21, 23, 25, 27, 29])

In [160]:
# 2 dim slicing

In [161]:
m = np.random.randint(10,size = (5,5))

In [162]:
m

array([[5, 0, 8, 3, 1],
       [6, 0, 0, 6, 2],
       [9, 2, 1, 0, 0],
       [3, 9, 0, 7, 1],
       [7, 8, 4, 8, 7]])

In [163]:
m[:,0]

array([5, 6, 9, 3, 7])

In [164]:
m[:,1]

array([0, 0, 2, 9, 8])

In [165]:
m[0,:]

array([5, 0, 8, 3, 1])

In [166]:
m[1,:]

array([6, 0, 0, 6, 2])

In [167]:
m[0:2,0:3]

array([[5, 0, 8],
       [6, 0, 0]])

In [169]:
m [:,:2]

array([[5, 0],
       [6, 0],
       [9, 2],
       [3, 9],
       [7, 8]])

In [170]:
m[1:3,0:2]

array([[6, 0],
       [9, 2]])

In [171]:
#subset operations

In [172]:
a = np.random.randint(10, size = (5,5))
a

array([[8, 6, 9, 5, 8],
       [3, 7, 6, 8, 1],
       [9, 0, 1, 8, 7],
       [9, 2, 5, 3, 8],
       [2, 8, 1, 5, 5]])

In [174]:
alt_a = a[0:3 , 0:2]
alt_a

array([[8, 6],
       [3, 7],
       [9, 0]])

In [175]:
alt_a[0,0] = 1000
alt_a[1,1] = 1000
alt_a

array([[1000,    6],
       [   3, 1000],
       [   9,    0]])

In [176]:
a

array([[1000,    6,    9,    5,    8],
       [   3, 1000,    6,    8,    1],
       [   9,    0,    1,    8,    7],
       [   9,    2,    5,    3,    8],
       [   2,    8,    1,    5,    5]])

In [177]:
# Subset effects main set

In [179]:
alt_b = a[0:3,0:2].copy()
alt_b

array([[1000,    6],
       [   3, 1000],
       [   9,    0]])

In [180]:
alt_b[0,0] = 0
alt_b[1,1] = 0
alt_b

array([[0, 6],
       [3, 0],
       [9, 0]])

In [181]:
a

array([[1000,    6,    9,    5,    8],
       [   3, 1000,    6,    8,    1],
       [   9,    0,    1,    8,    7],
       [   9,    2,    5,    3,    8],
       [   2,    8,    1,    5,    5]])

In [182]:
# Subset does not effect main set w/Copy() 

In [ ]:
#FANCY

In [185]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [187]:
v[1]

np.int64(3)

In [188]:
v[3]

np.int64(9)

In [189]:
[v[1],v[3]]

[np.int64(3), np.int64(9)]

In [190]:
fancy = [1,3]

In [191]:
v[fancy]

array([3, 9])

In [192]:
# 2 dim fancy

In [193]:
m = np.arange(9).reshape((3,3))

In [194]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [195]:
x = np.array([0,1])
y = np.array([1,2])

In [198]:
m[x,y]

array([1, 5])

In [200]:
m[0,[1,2]]

array([1, 2])

In [201]:
m[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [202]:
# IF ELSE

In [206]:
v = np.array([1,2,3,4,5])

In [207]:
v < 3

array([ True,  True, False, False, False])

In [208]:
v [v < 3]

array([1, 2])

In [209]:
v [v > 3]

array([4, 5])

In [210]:
v [v == 3]

array([3])

In [211]:
v

array([1, 2, 3, 4, 5])

In [213]:
# Mathematical Operations

In [214]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [215]:
v-1

array([0, 1, 2, 3, 4])

In [216]:
v * 2

array([ 2,  4,  6,  8, 10])

In [217]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [218]:
# ufunc

In [219]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [220]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [221]:
np.multiply(v,3)

array([ 3,  6,  9, 12, 15])

In [223]:
np.absolute(np.array([-3 ,-2]))

array([3, 2])

In [224]:
np.sin(360)

np.float64(0.9589157234143065)