In [4]:
#Pandas series

In [3]:
import pandas as pd

In [6]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [7]:
seri = pd.Series([10,88,3,4,5])
type(seri)

pandas.core.series.Series

In [8]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [9]:
seri.size

5

In [10]:
seri.values

array([10, 88,  3,  4,  5])

In [11]:
seri

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [12]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [13]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

In [14]:
# change index

In [16]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [24]:
seri = pd.Series([99,22,332,94,5] , index = ["a","b","c","d","e",])

In [25]:
seri["a"]

np.int64(99)

In [26]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [30]:
sozluk = pd.Series({"reg":10, "log":11,"cart":12})

In [31]:
seri = pd.Series(sozluk)

In [32]:
seri

reg     10
log     11
cart    12
dtype: int64

In [33]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [4]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
a

array([  1,   2,  33, 444,  75])

In [36]:
seri[0]

np.int64(1)

In [37]:
seri[0:3]

0     1
1     2
2    33
dtype: int64

In [39]:
seri = pd.Series([121,200,150,99] , index = ["reg" , "log" , "a" , "xxx"])

In [40]:
seri

reg    121
log    200
a      150
xxx     99
dtype: int64

In [41]:
seri.index

Index(['reg', 'log', 'a', 'xxx'], dtype='object')

In [42]:
seri.keys

<bound method Series.keys of reg    121
log    200
a      150
xxx     99
dtype: int64>

In [43]:
list(seri.items())

[('reg', 121), ('log', 200), ('a', 150), ('xxx', 99)]

In [44]:
seri.values

array([121, 200, 150,  99])

In [45]:
#eleman sorgulama

In [46]:
"a" in seri

True

In [47]:
"b" in seri

False

In [48]:
seri[["reg","a"]]

reg    121
a      150
dtype: int64

In [49]:
seri["reg"]

np.int64(121)

In [50]:
seri["reg"] = 1111
seri

reg    1111
log     200
a       150
xxx      99
dtype: int64

In [53]:
seri["reg":"a"]

reg    1111
log     200
a       150
dtype: int64

In [59]:
m = np.arange(1,10).reshape((3,3))

In [60]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
pd.DataFrame(m,columns = ["var1","var2","var3"])

,var1,var2,var3
0,1,2,3
1,4,5,6
2,7,8,9


In [62]:
df = pd.DataFrame(m,columns = ["var1","var2","var3"])

In [63]:
df

,var1,var2,var3
0,1,2,3
1,4,5,6
2,7,8,9


In [64]:
df.columns = ("deg1","deg2","deg3")

In [65]:
df

,deg1,deg2,deg3
0,1,2,3
1,4,5,6
2,7,8,9


In [66]:
df.axes


[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [67]:
df.shape

(3, 3)

In [68]:
df.ndim

2

In [69]:
df.size

9

In [70]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a = np.array([11,22,33,44,55])
a

array([11, 22, 33, 44, 55])

In [73]:
pd.DataFrame(a,columns = ["deg1"])

,deg1
0,11
1,22
2,33
3,44
4,55


In [5]:
s1 = np.random.randint(10,size=5)
s2 = np.random.randint(10,size=5)
s3 = np.random.randint(10,size=5)

In [7]:
sozluk = {"var1" : s1 , "var2" : s2 , "var3" : s3}

In [8]:
sozluk

{'var1': array([0, 8, 1, 9, 8]),
 'var2': array([1, 7, 9, 0, 6]),
 'var3': array([6, 1, 6, 0, 4])}

In [17]:
df = pd.DataFrame(sozluk)

In [18]:
df

,var1,var2,var3
0,0,1,6
1,8,7,1
2,1,9,6
3,9,0,0
4,8,6,4


In [20]:
df.loc[1,"var1"] = 999
df

,var1,var2,var3
0,0,1,6
1,999,7,1
2,1,9,6
3,9,0,0
4,8,6,4


In [21]:
#delete

In [24]:
df.drop(0 , axis = 0 , inplace = True)

In [25]:
df

,var1,var2,var3
1,999,7,1
2,1,9,6
3,9,0,0
4,8,6,4


In [26]:
#fancy

In [28]:
l = [2,4]
df.drop(l,axis = 0)

,var1,var2,var3
1,999,7,1
3,9,0,0


In [29]:
l = ["var1","var2","var4"]
for i in l:
    print(i in df)

True
True
False


In [30]:
df

,var1,var2,var3
1,999,7,1
2,1,9,6
3,9,0,0
4,8,6,4


In [33]:
df["var4"] = df["var1"] * df["var2"]
df

,var1,var2,var3,var4
1,999,7,1,6993
2,1,9,6,9
3,9,0,0,0
4,8,6,4,48


In [34]:
df

,var1,var2,var3,var4
1,999,7,1,6993
2,1,9,6,9
3,9,0,0,0
4,8,6,4,48


In [35]:
df.drop("var4" , axis = 1 , inplace = True)

In [36]:
df

,var1,var2,var3
1,999,7,1
2,1,9,6
3,9,0,0
4,8,6,4


In [38]:
#loc 

In [39]:
m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m,columns = ["var1","var2","var3"])

In [40]:
df

,var1,var2,var3
0,26,8,27
1,6,6,26
2,8,5,12
3,24,29,20
4,7,22,8
5,20,12,15
6,23,22,15
7,20,23,6
8,4,16,1
9,19,18,18


In [41]:
df.loc[0:3]

,var1,var2,var3
0,26,8,27
1,6,6,26
2,8,5,12
3,24,29,20


In [42]:
#iloc
df.iloc[0:3]

,var1,var2,var3
0,26,8,27
1,6,6,26
2,8,5,12


In [43]:
df.iloc[0,0]

np.int64(26)

In [44]:
df.iloc[:3,:1]

,var1
0,26
1,6
2,8


In [45]:
df

,var1,var2,var3
0,26,8,27
1,6,6,26
2,8,5,12
3,24,29,20
4,7,22,8
5,20,12,15
6,23,22,15
7,20,23,6
8,4,16,1
9,19,18,18


In [46]:
df[df.var1 >15]

,var1,var2,var3
0,26,8,27
3,24,29,20
5,20,12,15
6,23,22,15
7,20,23,6
9,19,18,18


In [47]:
df

,var1,var2,var3
0,26,8,27
1,6,6,26
2,8,5,12
3,24,29,20
4,7,22,8
5,20,12,15
6,23,22,15
7,20,23,6
8,4,16,1
9,19,18,18


In [49]:
df2 = df + 100
df2

,var1,var2,var3
0,126,108,127
1,106,106,126
2,108,105,112
3,124,129,120
4,107,122,108
5,120,112,115
6,123,122,115
7,120,123,106
8,104,116,101
9,119,118,118


In [53]:
pd.concat([df,df2], ignore_index=True)

,var1,var2,var3
0,26,8,27
1,6,6,26
2,8,5,12
3,24,29,20
4,7,22,8
5,20,12,15
6,23,22,15
7,20,23,6
8,4,16,1
9,19,18,18


In [57]:
df1 = pd.DataFrame({
    'calisanlar': ['Ali','Veli','Ayse','Fatma'],
    'grup': ['Muhasebe','Muhendislik','Muhendislik','IK']
})

df1

,calisanlar,grup
0,Ali,Muhasebe
1,Veli,Muhendislik
2,Ayse,Muhendislik
3,Fatma,IK


In [71]:
df2 = pd.DataFrame({
    'calisanlar': ['Ali','Veli','Ayse','Fatma'],
    'giris': [2023,2010,2016,1999]
})
df2

,calisanlar,giris
0,Ali,2023
1,Veli,2010
2,Ayse,2016
3,Fatma,1999


In [75]:
df3 = pd.merge(df1,df2)
df3

,calisanlar,grup,giris
0,Ali,Muhasebe,2023
1,Veli,Muhendislik,2010
2,Ayse,Muhendislik,2016
3,Fatma,IK,1999


In [76]:
df4 = pd.DataFrame({
    'grup' : ['Muhasebe','Muhendislik','IK'],
    'mudur' : ['Ahmet','Mehmet','Mahmut']
})
df4

,grup,mudur
0,Muhasebe,Ahmet
1,Muhendislik,Mehmet
2,IK,Mahmut


In [78]:
pd.merge(df3, df4)

,calisanlar,grup,giris,mudur
0,Ali,Muhasebe,2023,Ahmet
1,Veli,Muhendislik,2010,Mehmet
2,Ayse,Muhendislik,2016,Mehmet
3,Fatma,IK,1999,Mahmut


In [80]:
# count() first() last() median() mean() min() max() std() var() sum()



In [81]:
import seaborn as sns

In [82]:
df = sns.load_dataset("planets")

In [83]:
df

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300000,7.10,77.40,2006
1,Radial Velocity,1,874.774000,2.21,56.95,2008
2,Radial Velocity,1,763.000000,2.60,19.84,2011
3,Radial Velocity,1,326.030000,19.40,110.62,2007
4,Radial Velocity,1,516.220000,10.50,119.47,2009
...,...,...,...,...,...,...
1030,Transit,1,3.941507,NaN,172.00,2006
1031,Transit,1,2.615864,NaN,148.00,2007
1032,Transit,1,3.191524,NaN,174.00,2007
1033,Transit,1,4.125083,NaN,293.00,2008


In [85]:
df.head()

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300,7.10,77.40,2006
1,Radial Velocity,1,874.774,2.21,56.95,2008
2,Radial Velocity,1,763.000,2.60,19.84,2011
3,Radial Velocity,1,326.030,19.40,110.62,2007
4,Radial Velocity,1,516.220,10.50,119.47,2009


In [86]:
df.shape

(1035, 6)

In [89]:
df["mass"].mean()

np.float64(2.6381605847953216)

In [90]:
df["mass"].min()

0.0036

In [92]:
df["mass"].std()

3.8186166509616046

In [93]:
df.describe()

,number,orbital_period,mass,distance,year
count,1035.000000,992.000000,513.000000,808.000000,1035.000000
mean,1.785507,2002.917596,2.638161,264.069282,2009.070531
std,1.240976,26014.728304,3.818617,733.116493,3.972567
min,1.000000,0.090706,0.003600,1.350000,1989.000000
25%,1.000000,5.442540,0.229000,32.560000,2007.000000
50%,1.000000,39.979500,1.260000,55.250000,2010.000000
75%,2.000000,526.005000,3.040000,178.500000,2012.000000
max,7.000000,730000.000000,25.000000,8500.000000,2014.000000


In [94]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0
