Create NumPy Arrray

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
type(a)


numpy.ndarray

In [7]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [9]:
#sıfırdan array oluşturmak

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [14]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
np.random.normal(10,4,(3,4))

array([[ 7.89314065,  8.96133244, 14.54402154, 15.02225047],
       [10.8484422 , 10.48228894, 11.42297705, 10.20472989],
       [ 5.17300399, 14.24154517,  8.08302107, 16.92260659]])

In [17]:
np.random.randint(0,10,(3,3))

array([[7, 9, 0],
       [9, 9, 0],
       [9, 3, 2]])